insert into balancers(name)
values ('balancer-a'),
       ('balancer-b'),
       ('balancer-c'),
       ('balancer-d'),
       ('balancer-e'),
       ('balancer-f');

insert into machines(balancer_id, state)
values (1, false),
       (2, true),
       (1, true),
       (1, true),
       (2, false),
       (5, true),
       (6, false),
       (1, true),
       (3, true),
       (3, true),
       (3, true),
       (3, true),
       (2, true),
       (3, true),
       (2, false),
       (2, true),
       (2, false),
       (4, false),
       (6, true),
       (1, false),
       (2, false),
       (2, true),
       (5, false),
       (5, false),
       (3, true),
       (4, false),
       (3, true),
       (4, false),
       (4, false),
       (5, false),
       (5, false),
       (6, false),
       (1, false),
       (6, true),
       (3, true),
       (2, true),
       (2, false),
       (1, true),
       (5, false),
       (5, false),
       (4, false),
       (2, false),
       (6, true),
       (3, true),
       (5, true),
       (4, false);